### ISSUE TITLE
I like syntax HL

### ISSUE THREAD

**Issue by fagci** [phillbush/calendar#1]
Going forward your issue about -f argument, propose to upgrade shebang with
`#!/usr/bin/env -S awk -f ${_} --`

**Comment by phillbush** [comment]
Shebangs with more than one argument are not portable and, most importantly, do not work on the operating system I use.  
In the system I use, OpenBSD, only one argument is allowed for the shebang, everything after the first argument is considered to be part of the first argument itself.  
More information [here](https://man.openbsd.org/script.7#Portability_Note:_Multiple_arguments).
